[package]
name = "cincinnati-graph-data"
version = "0.1.0"
authors = ["Vadim Rutkovsky <vrutkovs@redhat.com>"]
edition = "2018"

[dependencies]
cincinnati = { git = "https://github.com/openshift/cincinnati", rev = "664ecb731df4a85c77c797563b084958058f11fd"}
tokio = { version = "0.2.11", features = [ "fs", "stream" ] }
serde = "^1.0.70"
serde_yaml = "^0.8.11"
serde_derive = "^1.0.70"
serde_json = "^1.0.59"
anyhow = "1.0"
regex = "^1.1.0"
semver = { version = "^0.9.0", features = [ "serde" ] }
toml = "^0.4.10"
protoc = "=2.8.0"
protobuf = "=2.8.0"
lazy_static = "^1.2.0"
url = "^2.1.0"
reqwest = { version = "^0.10", features = ["gzip"] }
futures = "^0.3"
gpgrv = "^0.3"
tempfile = "^3.1.0"
